Add Simulation and it's interface
Riwuko/inzynierka-django-server pull request #2
Opened 2020-11-08 20:03 UTC by Riwuko

2020-11-09 08:05 UTC, michalinaasd requested changes

2020-11-09 08:05 UTC, michalinaasd commented on Simulation/Environment.py
> +        self.blinds_state = "up"
zamień te stringi na boola 0 - off, 1 - on

2020-11-09 09:07 UTC, Riwuko commented on Simulation/Environment.py
> +        self.blinds_state = "up"
nie 0 i 1 tylko True i False i daj zmienną w stylu "heater_state_on = False" , jesteśmy w Pythonie nie w C <3 ale bardzo popieram bo magic strings to super słabo xD

2020-11-09 09:08 UTC, michalinaasd commented on Simulation/Environment.py
> +        self.blinds_state = "up"
to miałam na myśli XD

2020-11-09 09:13 UTC, michalinaasd commented on Simulation/Environment.py
> +        self.blinds_state = "up"
chociaż w sumie czy nie lepszy będzie enum? bo tak to mamy dwa stany - on, off. I myślę czy nie przyda się jeszcze disabled

2020-11-10 11:30 UTC, michalinaasd approved these changes

2020-11-10 11:30 UTC, merged